spring.application.name=aws-file-storage-app
spring.servlet.multipart.max-file-size=50MB
#spring.datasource.url=jdbc:postgresql://my-first-db-2026.cckwa19cla27.us-east-1.rds.amazonaws.com:5432/awsfilestoragedb
#spring.datasource.username=postgres
#spring.datasource.password=pass123?!

# Secrets Manager
spring.config.import=aws-secretsmanager:aws-file-storage-secrets
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.root=INFO
logging.level.com.awsfilestorage=DEBUG